/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lqpRhXyxpme
 */
import Link from "next/link"
import { JSX, SVGProps } from "react"

export function App() {
  return (
    <div key="1" className="dark flex flex-col min-h-screen bg-gray-900">
      <main className="flex-1 py-10 px-4 bg-gray-800 bg-opacity-50">
        <section className="container mx-auto space-y-6 text-center" id="about">
          <div className="mx-auto max-w-2xl bg-gray-800 p-8 rounded-lg shadow-lg">
            <h1 className="text-4xl font-bold text-gray-100">Victor Assis</h1>
            <p className="text-gray-400 mt-4">
              I am a computational biology researcher and computer engineering undergraduate student at Insper -
              Instituto de Ensino e Pesquisa (Brazil). My work focuses on developing computational models to understand
              biological systems and tools to help researchers in their own research.
            </p>
            <p className="text-gray-400 mt-4">
              My research interests include single-cell omics, machine learning, and drug discovery. I am currently a
              research intern at University of Cincinnati College of Medicine's THINK Lab, where I am focusing on the
              development of tools to facilitate omics and health research under the supervision of Lucas Bulgarelli.
            </p>
            <p className="text-gray-400 mt-4">
              Previus to that, I was working on automatic single-cell annotation as a volunteer researcher at the
              Computational Systems Biology Lab at São Paulo University (USP) under the supervision of Prof. Dr. Helder
              Nakaya. On a past live, I also worked as a Product & Data Analyst at a BNPL Colombian startup called Addi,
              backed by Andreessen Horowitz.
            </p>
            <p className="text-gray-400 mt-4">
              I recently got selected to participate in the 2024 Summer Research Program at the University of Illinois
              at Urbana-Champaign, where I will be working on (To be defined). This opportunity was made possible by the
              partnership between Insper and the University of Illinois at Urbana-Champaign. Thanks, Insper!
            </p>
            <p className="text-gray-400 mt-4">
              My goal is to pursue a PhD in computational biology and, by the end of my doctoral studies, to start my
              own biotech company. I am currently looking for a PhD position in computational biology or related fields.
              If you are interested in my work, please feel free to contact me at hey@victorassis.com or by clicking the
              mail icon below.
            </p>
            <img
              alt="Victor Assis"
              className="mt-8 mx-auto w-48 h-48 object-cover rounded-full border-4 border-gray-700"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
            <div className="flex justify-center space-x-4 mt-8">
              <Link className="text-gray-400 hover:text-gray-300" href="#">
                <TextIcon className="h-6 w-6" />
              </Link>
              <Link className="text-gray-400 hover:text-gray-300" href="#">
                <GithubIcon className="h-6 w-6" />
              </Link>
              <Link className="text-gray-400 hover:text-gray-300" href="#">
                <LinkedinIcon className="h-6 w-6" />
              </Link>
              <Link className="text-gray-400 hover:text-gray-300" href="#">
                <MailIcon className="h-6 w-6" />
              </Link>
            </div>
          </div>
        </section>
      </main>
      <footer className="w-full py-6 px-4 bg-gray-800 shadow-md">
        <div className="container mx-auto flex items-center justify-center">
          <p className="text-gray-400">© 2024 Victor Assis. All rights reserved.</p>
        </div>
      </footer>
    </div>
  )
}


function TextIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 6.1H3" />
      <path d="M21 12.1H3" />
      <path d="M15.1 18H3" />
    </svg>
  )
}


function GithubIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0-1-3.5c3 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2c-.3 1.15-.3 2.35 3.5A5.403 5.403 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function LinkedinIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 1 6v7h-4v-7a2 2 0-2-2 0-2 2v7h-4v-7a6 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function MailIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 1-2.06 0L2 7" />
    </svg>
  )
}
